### PR TITLE
A few small updates

### PR DESCRIPTION
**Pull request by k6ps**
Hi! I updated a the base image version from MS, and added a few comments to readme.

### CODE REVIEW

**Comment by garyritchie** [comment]
Additional notes are super helpful and I'm considering [a semi-automated fix](https://www.laurivan.com/fix-standard_init_linux-goxxx-exec-user-process-caused-no-such-file-or-directory-error/) for one of my own images that involves running `dos2unix` -- just in case line endings get goofed up again.

**Comment by cfritschi** [comment]
The changes from "k6ps" are exactly what I also need to change!

**Comment by shanegenschaw** [comment]
Thanks for the updates!

**Comment by cfritschi** [comment]
Hi 
I had a problem by creating the Docker-Image base scripts in Windows and run the Docker-Image on a Linux.
I had to add the following commands to the Dockerfile:
RUN chmod a+x /usr/local/bin/docker-entrypoint.sh && chmod a+x /usr/local/bin/docker-entrypoint-initdb.sh

**Pull request merged**
